require 'rake'
require 'fileutils'

task :default => :jboss_install

jboss_zip = "target/jboss_as_7.1.1.zip"
jboss_destination = "vendor/jboss_as"

def unzip(src, dst)
  run_command "unzip -o #{src} -d #{dst}"
end

def wget(link, dst)
  run_command "wget #{link} -O #{dst}"
end

def run_command(command)
  success = system(command)
  success && $?.exitstatus == 0
end

desc "Download jboss AS 7.1.1"
task :jboss_download do
  FileUtils.mkdir_p "target"
  unless File.exists?(jboss_zip)
    puts "Downloading JBoss AS 7.1.1"
    wget("http://download.jboss.org/jbossas/7.1/jboss-as-7.1.1.Final/jboss-as-7.1.1.Final.zip", jboss_zip)
  end
end

task :jboss_unzip do
  unzip(jboss_zip, jboss_destination)
end


desc "Patch resteasy in JBoss to 3.0.9 version"
task :patch_resteasy do
  puts "monkey patch jboss with resteasy 3.0.9 now..."
  modules_path = "#{jboss_destination}/jboss-as-7.1.1.Final/modules"
  FileUtils.rm_r "#{modules_path}/org/jboss/resteasy/"
  unzip("vendor/resteasy-jboss-modules-3.0.9.Final.zip", modules_path)
end

desc "Install JBoss AS 7.1.1 in target/jboss-as-7.1.1 and monkey patch resteasy"
task :jboss_install => [:jboss_download, :jboss_unzip, :patch_resteasy] do
end

